---
language: node_js
node_js:
  - "stable"

addons:
  sauce_connect: true

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "cd kujira"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
